### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Motzee** [Motzee/minitchat#1]
Reste à faire :
- [x] break words pour éviter la déformation 
- [x] Vider l'input quand message posté
- [ ] inverser la présentation des message (ou scroll auto)
- [ ] antiflood
- [ ] liste des personnes connectées active
- [ ] menu dynamique de changement de salon
- [ ] système d'inscription et de session (checking ajax des alias pour ne pas prendre un pseudo réservé)
- [ ] anti-doubles
- [ ] chrome et safari : déformation de la largeur (ascenseur pour les personnes connectées) si post très très long
